### ISSUE TITLE
Beta1.7 ckeditor

### ISSUE THREAD

**Issue by gvoxcms** [cmsimple-xh/cmsimple-xh#213]
I think You sholud have modern templates like Bootstrap(bootstrap-plugin) for tinymce and material and pure  as examples. The ckeditor 4 is quite unstabel in this version

**Comment by cmb69** [comment]
The [TinyMCE Bootstrap plugin](https://codecanyon.net/item/tinymce-bootstrap-plugin/10086522) is payware, and as such doesn't fit to our Open-Source model. 

Adding Google's material design icons would have been a reasonable alternative to Font Awesome, but it has been decided not to add any icon font to the core (for now), but rather to deliver Font Awesome as plugin. The same could be done for the material icons, but I'm not sure whether that would be the best idea, as some users/designers/developers might use one and others the other, what would lead to fragmentation instead of consistency.

With regard to Bootstrap, Pure or other CSS frameworks im reluctant to include these in the core. Certainly they are not needed for many CMSimple_XH websites, and everybody might prefer one or another. Besides, such Frameworks could be supported by a CMSimple_XH plugin.

@TN03 is already working on a new version of CKEditor.

IMHO, this ticket can be closed as WONTFIX. But others might have a different opinion. :)

**Comment by TN03** [comment]
> IMHO, this ticket can be closed as WONTFIX

+1
