### ISSUE TITLE
filebrowser & SVG

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#294]
Der Filebrowser kann SVG nicht in der Vorschau anzeigen (hover).

**Comment by cmb69** [comment]
Confirmed. The problem is [this line](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/plugins/filebrowser/classes/View.php#L320). Firstly, [`isImageFile()`](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/plugins/filebrowser/classes/View.php#L247-L252) doesn't respect the configured file extensions, but rather uses a hard-coded list. Secondly, `getimagesize()` [does not (yet) support SVG](https://bugs.php.net/bug.php?id=71517). The first issue is certainly a bug in CMSimple_XH, but I'm not sure about the second issue. Maybe we should rid the [pseudo-resizing code](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/plugins/filebrowser/classes/View.php#L380-L385), and use CSS instead.

**Comment by frase-git** [comment]
Falls `getimagesize()` hier wirklich nur für die Anzeige der Bildgröße bei der Vorschau verwendet wird(?), könnte man vielleicht bei SVG darauf verzichten? Das Bild (sofern möglich/ nach Fix) aber trotzdem anzeigen?
Da müsste man evtl. eine maximale Größe festlegen (wie übrigens bei allen anderen Bildern auch).

Und, wenn schon jemand an den Filebrowser rangeht: FA-Icons und eindeutige Klassen. (nur sekundärer Wunsch.)

**Comment by cmb69** [comment]
> Da müsste man evtl. eine maximale Größe festlegen (wie übrigens bei allen anderen Bildern auch).

Ginge wohl mit `max-width: 150px; max-height: 150px` was aber bei SVG nicht funktioniert. Und wenn ich mir https://css-tricks.com/scale-svg/ anschaue, wird mir schwindlig. Vielleicht sollten wir bei SVG doch lieber auf die Vorschau verzichten.

Wie machen das eigentlich KCFinder und elFinder?

**Comment by frase-git** [comment]
> Wie machen das eigentlich KCFinder und elFinder?

leider keine Zeit-Ahnung ;-)

Im Filebrowser könnte man neben der Bilderliste einen festen Rahmen (absolute) platzieren, in dem die Bilder angezeigt werden. In meinem Test für xh-org auf bplaced habe ich das XH-Logo als SVG 3 mal drin.
Entweder als Background-Image `background-size: contain;` oder ganz oben links als normales Bild in einem festen Container.

**Comment by cmb69** [comment]
> Wie machen das eigentlich KCFinder und elFinder?

Beide zeigen SVGs als Textdateien (Standard-Icon) an – eine Vorschau ist nicht verfügbar.

> Im Filebrowser könnte man neben der Bilderliste einen festen Rahmen (absolute) platzieren, in dem die Bilder angezeigt werden.

Klingt nicht verkehrt, aber am Filebrowser möchte ich möglichst wenig ändern bevor er nicht überarbeitet wurde. Da geht es mir für meinen Geschmack doch recht wild zu: Controller-Code in admin.php, Model Code im Controller, und fehlende Templates (z.B. [hier](https://github.com/cmsimple-xh/cmsimple-xh/blob/1.7.0/plugins/filebrowser/classes/View.php#L283-L311)). Und auch die bestehenden Templates müssten IMHO unbedingt überarbeitet werden. So wie es jetzt ist, ist die Sicherheit "Glückssache", und nur dadurch gegeben, dass der Filebrowser nur im Adminmodus aufgerufen werden kann (was vermutlich kein Dauerzustand sein sollte).

Da auch die beiden "dicken" Filebrowser (noch) keine SVG-Voransicht bieten, sehe ich da allerdings auch keinen dringenden Handlungsbedarf.
