### ISSUE TITLE
Some languages wont show seperate login form

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#295]
In loginforms() the global $f is overwritten by the localized $tx['menu']['login']. Don't know why. In the Dutch case, this is "Inloggen". Therefore in cms.php 1325 the wrong themplate is chosen.

**Comment by cmb69** [comment]
> In loginforms() the global $f is overwritten by the localized $tx['menu']['login']. Don't know why.

Because CMSimple sets the [page title to `$f`](https://github.com/cmsimple-xh/cmsimple-xh/blob/master/cmsimple/cms.php#L1315-L1318) if not already set, confusing model values (`$f`) and view values (`$title`).

Apparently, the only other case where this happens in the standard distro is wrt. the [site-info](https://github.com/cmsimple-xh/cmsimple-xh/blob/master/cmsimple/cms.php#L1182) which has to be fixed as well.

To avoid future issues in this regard, we should consider to remove the fallback on [using `$f` as `$title`](https://github.com/cmsimple-xh/cmsimple-xh/blob/master/cmsimple/cms.php#L1315-L1318) altogether.

**Comment by manu37** [comment]
But then at least set [$f](https://github.com/cmsimple-xh/cmsimple-xh/blob/master/cmsimple/functions.php#L1566) to a static 'login'. And try to set the $title with a localized $tx[menu][$f] if present.

**Comment by cmb69** [comment]
> But then at least set $f to a static 'login'. And try to set the $title with a localized $tx[menu][$f] if present.

Yes, that's what I meant.
