### ISSUE TITLE
deprecated  get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by gtbu** [cmsimple-xh/cmsimple-xh#399]
In functions.php is
581 function stsl($t)
{     return get_magic_quotes_gpc() ? stripslashes($t) : $t;
}
get_magic_quotes_gpc() is deprecated since php5.4 - needs a solution like
https://stackoverflow.com/questions/17185325/php-5-4-magic-quotes-gpc-alternative

**Comment by TN03** [comment]
Good catch, thanks. But we don't need an alternative, since without "magic_quotes" stripslashes() becomes useless in our case. In other words: since PHP 5.4 [function stsl($t)](https://github.com/olape-git/cmsimple-xh/blob/62cffd36799c51abc9ba72732b9d9e3ad24de15e/cmsimple/functions.php#L581) always returns $t unmodified, because get_magic_quotes_gpc() always returns 0.
I would propose to change stsl() to just return $t, trigger a E_USER_DEPRECATED warning and put the code to [compat.php](https://github.com/olape-git/cmsimple-xh/blob/master/cmsimple/compat.php).

BTW: we should add PHP 7.4 to Travis CI and our test - cases. 

And both ASAP, with the next release (1.7.3) which is in progress at the moment.

**Comment by olape-git** [comment]
> I would propose to change stsl() to just return $t, trigger a E_USER_DEPRECATED warning and put the code to  compat.php.

Yes, is the best way.

**Comment by gtbu** [comment]
Hm... but the code should be corrected so that the error does not come up !

**Comment by TN03** [comment]
> Still - the code should be corrected so that the error does not come up !

Of course it has to be. Function stsl($t) should only return $t unmodified, if PHP-version is <5.4. I'll provide a PR ASAP. BTW: it seems to be a good idea for me to lift the requirements above PHP 5.3. (mabe 5.6), so we can rid stsl() from the core.

> If You prepare the next version : Evtl. You can add some variables like $asset and $plugindir and $themedir - this avoids code with __ DIR __ . '/abc ...

Using global variables for such things is not a good idea at all. We already have enough of them for historical reasons and it wold be good if we could rid them. But this is not an option for now for a lot of reasons. A better choice might be some kind of API IMO. And, to be honest, I can't remember that I have used such code with __ DIR __ . Have you noticed the contents of $pth - array? There is already $pth['folder']['templates'], $pth['folder']['template'], $pth['folder']['plugins'], $pth['folder']['plugin'] ... and so on. You should give var_dum($pth) a try. So no need for new globals.
For further informations our [Dev-Doc](https://dev-doc.cmsimple-xh.org/) might be useful.

> Also CMSIMPLE_URL should be replaced with a safe code without the use of HTTP_HOST .

That's not that easy. Ideas? Anyway, even HTTP_HOST _might_ be unsafe -- it belongs to the context. Can you bring some light to this? Why exactly is it unsafe the way it's used. And, to be honest, I have no idea how to build CMSIMPLE_URL without it.

BTW: it would be nice if you open different issues for different things. Otherwise it becomes hard to decide to close an issue.

**Comment by gtbu** [comment]
I did not know var_dum($pth) etc.. - though i prefer $plugindir etc.
HTTP_HOST is unsafe because of spoofing and XSS (was already mentioned in the forum) . In my clean-filter i hardened it with gzipping the 301-buffer, which is then difficult to spoof.
At the moment i do not know another solution but i will  look in the internet.

**Comment by olape-git** [comment]
> Why exactly is it unsafe

All elements of the $_SERVER array whose keys start with 'HTTP_' are taken from HTTP request headers and are therefore not safe.
But, I think it still depends on the server configuration if you can manipulate it.

### But now back to the topic!

PHP 5.6 for the 1.7.3?
Wouldn't that be better for the 1.8?
Well, in principle I have nothing against it, I also hope that almost nobody uses 5.3 anymore.

**Comment by TN03** [comment]
> But now back to the topic!

+1

> Wouldn't that be better for the 1.8?

Yes, you're right. So I'll suggest to use version_compare to rewrite stsl($t). But it might be a good idea to trigger a user-warning?

**Comment by olape-git** [comment]
> So I'll suggest to use version_compare to rewrite stsl($t).

Das ist wieder so eine GitHub-Sache? Da bin ich überfragt. Ich hätte die Funktion einfach, wie oben beschrieben, nach compat.php verschoben.

> But it might be a good idea to trigger a user-warning?

yes

**Comment by TN03** [comment]
@olape-git Not a Github thing. As long as we support PHP 5.3, we have to deal with magic quotes. Therefore we need stsl() as it is -- but now with a workaround for PHP 7.4. And as long as the core uses stsl(), we should not move it to compat.php IMHO.

**Comment by olape-git** [comment]
Okay, you got that right. Of course, if the function is used in the core, then we can't move it. I haven't followed it that far.
Can't we just query the PHP version within the function and react accordingly ?

**Comment by olape-git** [comment]
#403 
https://github.com/cmsimple-xh/cmsimple-xh/pull/403/commits/799b4a27816df78063b6011c5936d6502251b3b2
