### ISSUE TITLE
filebrowser - display used images

### ISSUE THREAD

**Issue by manu37** [cmsimple-xh/cmsimple-xh#481]
Used images in  media `<video poster="...">` are not recognized in preview, but alerted on delete. No big deal but might be nice to be corrected/completed.

**Comment by manu37** [comment]
The same for images used in `<a class="zoom" href"...">`

**Comment by cmb69** [comment]
Indeed, there is an ugly dichotomy. Used files are detected by https://github.com/cmsimple-xh/cmsimple-xh/blob/e3cc319f5317f6556bd23a68ad61e9209eab68b5/plugins/filebrowser/classes/Controller.php#L214
For deletion and renaming the detection is https://github.com/cmsimple-xh/cmsimple-xh/blob/e3cc319f5317f6556bd23a68ad61e9209eab68b5/plugins/filebrowser/classes/Controller.php#L186-L187

Apparently, both regexps should be identical. If there are performance issues, we could cache, unless we can improve the regexp. And frankly, we should likely use the DOM instead of regexps here.

**Comment by olape-git** [comment]
Hm, dein Vorschlage geht in diese Richtung?
[https://gist.github.com/pento/8034553](https://gist.github.com/pento/8034553)
Dann scheint regexps aber doch um einiges schneller.

**Comment by cmb69** [comment]
Ja, dürfte schneller sein, aber ist halt immer etwas frickelig für HTML; eine DOM-Lösung müssten wir wohl auf jeden Fall cachen.
