### ISSUE TITLE
Drop TinyMCE 4

### ISSUE THREAD

**Issue by cmb69** [cmsimple-xh/cmsimple-xh#507]
As of d53633d841d5d711f50c25c919b78f929d7f53aa, we have TinyMCE 5 bundled, and given that TinyMCE 4 is already unsupported, we should remove it with the next minor.

**Comment by frase-git** [comment]
Considering that TinyMCE5 still has (minor) problems and that some users don't want to change, I suggest to continue shipping TinyMCE4 - at least as a second option.

**Comment by manu37** [comment]
Could you explain what minor problems these are? Apart of some plugins require minimal/medium inits? 
The other problems i know are based on the missing config.php on update. IMHO not a TMCE5 Problem.
What else? We should focus on solving these problems, rather than supply an outdated editor. Or are there alternatives for an up to date RTE?

**Comment by cmb69** [comment]
I still think that we should unbundle TinyMCE 4 for XH 1.8. We can make a separate download  of TinyMCE 4 available, if there is still the need.

**Comment by frase-git** [comment]
Okay, you're probably both right. I'm happy to be outvoted here. Let's cut off "old habits" consistently. ;-)

**Comment by manu37** [comment]
I'm still open [for the best configuration option](https://www.tiny.cloud/docs/demo/full-featured/). A good moment to discuss this before 1.8.

**Comment by cmb69** [comment]
@manu37, might make more sense to discuss the configuration option in the forum to hopefully get some suggestions from end users, too.

**Comment by frase-git** [comment]
> ... discuss the configuration option in the forum ...

https://cmsimpleforum.com/viewtopic.php?f=12&t=18212
