### ISSUE TITLE
editorbrowser fails to select image when clicking on preview

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#522]
Concerns version XH 1.7.5RC1

`Insert/edit image` → `Source` → `click on preview image`

Error message in the console, see image:
![filebrowser-insert-images](https://user-images.githubusercontent.com/24246330/129440674-0079c426-5384-462f-b924-286e5cdf6ed4.png)

**Comment by lck-git** [comment]
Siehe dazu auch https://github.com/cmsimple-xh/cmsimple-xh/issues/517#issuecomment-897542961

**Comment by cmb69** [comment]
> Da sollte eigentlich das Bild in einem neuen Tab geöffnet werden, zumindest ist das so beim Dateimanager. Ich glaube das ist ein BUG.

The cmsbrowser does indeed open the image in a new tab. The editorbrowser, however, should insert the image path; that doesn't happen because we're using `event.target` instead of `event.currentTarget` (likely a relict of having IE 8 support, which supports neither property, but `event.srcElement`). If we wanted to support IE 8, we would have to traverse the DOM upwards until we find `event.currentTarget`, but since we dropped support for old IE already, the fix is trivial.

**Comment by frase-git** [comment]
> The editorbrowser, however, should insert the image path;

This is exactly how it should be.
https://github.com/cmsimple-xh/cmsimple-xh/commit/9654ef2f731125175ef9fa963d7b03659574315b corrects this cleanly and it works.

Now the cursor on the image should become a pointer.
Add to this [at this point](https://github.com/cmsimple-xh/cmsimple-xh/issues/517#issuecomment-897398291):

```
span.xhfbfile,
span.xhfbfile img {
    cursor: pointer;
}
```

**Comment by cmb69** [comment]
Is `span.xhfbfile img` necessary? Isn't the cursor inherited from `span.xhfbfile` anyway?

**Comment by cmb69** [comment]
Actually, `span.xhfbfile` should be `a.xhfbfile`, but that's better left to XH 1.8 for BC reasons.

**Comment by lck-git** [comment]
> Is `span.xhfbfile img` necessary? Isn't the cursor inherited from `span.xhfbfile` anyway?

You are right. Necessary is only:
`span.xhfbfile {
    cursor: pointer;
}`

**Comment by frase-git** [comment]
Sorry, you are both right.
Something got mixed up when I was testing.
Once is enough ;-)

**Comment by cmb69** [comment]
Fine. Done by a3ff7e7c6abb8f12184fdce8374c69b4df716068.
