### ISSUE TITLE
FA4 and FA 5 - Tinymce

### ISSUE THREAD

**Issue by g7sim** [cmsimple-xh/cmsimple-xh#528]
If i choose FA5 in the FA-plugin then Tinymce4  has no icons - difficult to patch - perhaps with a [fontawesome -plugin](https://github.com/josh18/TinyMCE-FontAwesome-Plugin) or else ?
I would personally drop FA4.7 and adapt the plugins

**Comment by cmb69** [comment]
Ah, indeed. TinyMCE 5 has the same issue. I'm somewhat surprised that this hasn't reported yet – or maybe I missed it. Anyhow, the problem is that the font name has been changed from `FontAwesome` to `Font Awesome 5 Free` (and there is also `Font Awesome 5 Brands`), and that a lot of icons are missing in the free FA 5 version (there may be some additional icons, though).

So yeah, the list of icons need to be revised; https://github.com/josh18/TinyMCE-FontAwesome-Plugin/commit/52c59de66fcf4bab45fdaf567272e1968f9d9f55 could help somewhat, but that is about FA 5 Pro, and I'm certainly not going to support that commercial stuff with unpaid FOSS work.

Actually, this should have been filed against https://github.com/cmb69/fa_xh (I cannot transfer the ticket due to different owners).

**Comment by g7sim** [comment]
I nearly fixed it in my XC - Version by updating the \fa\editors\tinymce4\fontawesome with the v5  version of the josh18-master.
But then FA4.7 isnt functioning (i dont need it).  A switch with query what was selected in the FA plug-in is probaly i bit extravagant

**Comment by cmb69** [comment]
Thanks for forwarding!
