### ISSUE TITLE
RCE in cmsimple-xh 1.7.6

### ISSUE THREAD

**Issue by ElnurBDa** [cmsimple-xh/cmsimple-xh#620]
Similarly to https://github.com/advisories/GHSA-56jv-hmch-qm6c , it is possible to upload a PHP payload to execute commands on the host. It requires being **Authenticated**.

Version: CMSimple_XH 1.7.6

https://github.com/ElnurBDa/cmsimple-xh-RCE-Authenticated-1.7.6

**Comment by cmb69** [comment]
Interestingly, just today I found a similar RCE in the Linux kernel. It is possible to install some software listening on an open port to public request (say httpd), which than triggers arbitrary code which I have configured. Of course, that requires adminstrative rights (i.e. user `root`).

Do you want to report it to them? Probably not, because you know that administrators are *supposed* to be able to do such things.

Same with CMSimple_XH. If you have admin rights, you can execute arbitrary PHP code, as it is supposed to be. So this is not a bug, let alone a security issue.

> It requires being **Authenticated**.

Note that CMSimple_XH is a single user system, so the authenticated user has administrative rights by design.

> https://github.com/ElnurBDa/cmsimple-xh-RCE-Authenticated-1.7.6

Way to complex. You can just write the code directly in the contents file, in the template or onto any page.

**Comment by ElnurBDa** [comment]
Okay
